export default function Head() {
  return (
    <>
      <title>Clip Hunter</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="Find the best moments from your longest VODS" content="Generated by create next app" />
      <link rel="icon" href="/pog.ico" />
    </>
  )
}
